### ISSUE TITLE
errors in set display for perfornance

### ISSUE THREAD

**Issue by FatBastard0** [ChrisTitusTech/winutil#2802] opened 2024-09-23 00:25 UTC
I get this
![ScreenShot_20240922171307](https://github.com/user-attachments/assets/7f456862-32a0-4d23-8e65-9f31b77be6a5)

I run winutil
I go to Tweaks
Advanced Tweaks
mark Set Display for Performance
Then "Run Tweaks"
and I get the above (ScreenShot)

I am on Windows 23H2
If you need any information form me let me know

**Comment by zmileski** [comment] 2024-09-23 01:35
#2769 dont open the same issue twice
https://github.com/ChrisTitusTech/winutil/issues/2769#issuecomment-2363991852 this is the fix if u want to fix
and wait for someone to make PR

**Comment by FatBastard0** [comment] 2024-09-23 19:23
Thanks for you reply and comment

However if you look at my last comment you would know that the reply did not fix the issuse. I was hope for a look at  he fact that I did the repair listed above and it did not work. I an thankful that you looked at it. I do not know why it did not work.
I did fix and tryed it, that did not work and I tried it with a reboot of the system and that did not work.

Please help me, I am new at this so I may have did the repair right. 
Thanks

**Comment by FatBastard0** [comment] 2024-09-23 22:38
Did this because email asked
![1](https://github.com/user-attachments/assets/9f94bc91-7ce4-424e-b2d1-9a81f991140e)
Rebooted
I get this 
![2](https://github.com/user-attachments/assets/3fc145d3-bf48-47c1-8022-35d6c6858cc3)

Thanks you so much!! 
You are the man!

**Comment by MyDrift-user** [comment] 2024-11-19 20:02
/close

- duplicate of #2769

**Closed** 2024-11-19 20:02 UTC
Labels: bug
