### ISSUE TITLE
Service "w32time" should not be set to manual

### ISSUE THREAD

**Issue by Double-A-92** [ChrisTitusTech/winutil#2311] opened 2024-07-09 13:59 UTC
**Describe the bug**
The service "w32time" gets set to manual start. 
This obviously stops the automatic time synching which causes your clock to slowly drift off (depending on your motherboards time keeping ability).

**To Reproduce**
1. Run the Tweaks to set most services to manual
2. Use windows for a few months
3. Time is about a minute off

**Expected behavior**
Leave w32time on automatic start, so this issue doesn't happen.

**Comment by Marterich** [comment] 2024-07-09 14:31
I'm fairly sure that the default startup type set by Microsoft for the w32time service is "manual" and not "automatic"
Afik the time synchronization works via scheduled tasks per default. (someone please correct me if I'm wrong)

Either way, a viable option could be to add a teak that implements the "high accuracy" mode for time which will guarantee <=1ms time deviation.

https://learn.microsoft.com/en-us/windows-server/networking/windows-time-service/configuring-systems-for-high-accuracy

**Comment by Double-A-92** [comment] 2024-07-09 14:50
Hmm yeah, you're right. It's even in the tweaks.json here: https://github.com/ChrisTitusTech/winutil/blob/af1743066f2891918fa4d31e0b929d2a1db7c016/config/tweaks.json#L1084

Now I wonder what else could have broken my time sync...

**Comment by Marterich** [comment] 2024-07-09 15:03
I think the following command will likely fix your problem.
```powershell 
w32tm.exe /config /manualpeerlist:”0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org,0x8″ /syncfromflags:manual /updateCopied
```

This command explicitly tells the time service to use the public, external NTP Servers to sync the time.
There is a full guide on https://theitbros.com/configuring-dc-for-sync-time-with-external-ntp-server/ but you should pretty much only need the given command (and maybe a service or system reboot) because (I assume) you don't have encountered the problem on a Domain Controller

**Comment by Marterich** [comment] 2024-07-16 19:37
As this issue doesn't seem to be caused by winutil and I don't think that many users need or want to configure the high precision time (and if they do, they have to set it up themselves to guarantee the accuracy) I'm going to close this issue. If you think there are still unanswered questions, please reopen or create a new issue
/close

**Closed** 2024-07-16 19:37 UTC
