### ISSUE TITLE
please add FanControl utility/tool

### ISSUE THREAD

**Issue by Evan-Galvin** [ChrisTitusTech/winutil#961] opened 2023-08-12 15:36 UTC
Would be a welcome addition to the installable app list...
FanControl:  https://github.com/rem0o/fancontrol.releases

project page is self explanatory.  Works very well, has many available plugins for increased functionality and 3rd party product compatibility.

Have not found a better program for this purpose.  The degree of configuration is unmatched by any other program/utility(be it a product offered by a manufacturer, or open-source)

**Comment by meenbeese** [comment] 2023-09-10 19:03
Duplicate of #444

**Closed** 2023-09-14 01:48 UTC
