### ISSUE TITLE
Installed Applications/Features do not appear in search

### ISSUE THREAD

**Issue by HonkinWaffles** [ChrisTitusTech/winutil#495] opened 2022-12-05 21:00 UTC
**Describe the bug**
Both Hyper-V and Teams do not get added to Windows search when installed via script. 

**To Reproduce**
1. Run script
2. Install Teams + Hyper-V
3. Reboot
4. Check search for Hyper-V

**Expected behavior**
Applications should show up in search

**Screenshots**
![image](https://user-images.githubusercontent.com/45575558/205741423-85a5b1de-b93e-468e-9c59-87222f355d1f.png)
![image](https://user-images.githubusercontent.com/45575558/205741819-51c13027-55b2-4865-aa0f-f72b78328d9d.png)

**Additional context**
None to add

**Comment by Adison-Masih** [comment] 2022-12-18 00:14
even i have faced this issue for not only Hyper-V but many programs such as brave, vs code, visual studio, powershell, OBS Studio, audacity etc.

**Comment by dreamsyntax** [comment] 2023-03-18 22:30
Duplicate of https://github.com/ChrisTitusTech/winutil/issues/69
But valid. I am able to reproduce. 
#69 not resolved.

**Closed** 2023-07-12 21:44 UTC
