### ISSUE TITLE
Bug Report: Microsoft.VCLibs.140.00 Download Failure

### ISSUE THREAD

**Issue by ahscolan2** [ChrisTitusTech/winutil#1640] opened 2024-02-22 00:36 UTC
When attempting to download the Microsoft.VCLibs.140.00 package from the "winget reinstall" option, the installation consistently fails with the following error message:
![Capture](https://github.com/ChrisTitusTech/winutil/assets/115270338/eae94678-ba4b-449c-b491-da5c02caa6a1)
Tried it on 5 different installs but wont work (win 10) but works for win 11

**Comment by micangl** [comment] 2024-02-24 14:25
I'm facing the same issue...

**Comment by og-mrk** [comment] 2024-02-27 18:48
Similar Issue to #1657 issue, please read the comments there for more info.
Once you're satisfied with the the answer over there, you can go ahead and close the issue, thanks for contributing to this project by reporting bugs, and have a nice day.

**Comment by Serggxx96** [comment] 2024-02-28 20:38
is this still an ongoing issue? because the same exact thing is going on with me, I'm a noob so any help/advice works!

**Comment by og-mrk** [comment] 2024-02-28 21:53
Unfortunately @Serggxx96, this issue is still present with `microsoft-vclibs-140-00` choco package, meaning that the Maintainers will be the one fixing the root cause of this issue, which's outside of WinUtil's Scope.

Luckily, because Chocolatey's Packages are Community-Based, meaning they have a [Repo](https://github.com/chocolatey-community/chocolatey-packages) that anyone can contribute & report issue(s) about a specific package and so on... I've reported [an issue](https://github.com/chocolatey-community/chocolatey-packages/issues/2436) on `microsoft-vclibs-140-00` package, with additional info on Why this problem is happening in the first place, which I've found out with some patience and Tracing the Output Log.

Also I know one might say "If it's a simple problem, why wouldn't someone fixed it already?!", and the simple answer to this.. is that Project & Package Maintainers are Human as well, they have a life of their own, work, may be a family to take care of, and some hobbies here and there, there's only some much time one could spare for things like Open Source Contributions.
So please... be patient, and the issue at hand will be fixed soon.. And have a nice day 😄

**Closed** 2024-03-15 00:09 UTC
