### ISSUE TITLE
script not starting

### ISSUE THREAD

**Issue by pigale88** [ChrisTitusTech/winutil#99] opened 2022-08-06 18:46 UTC
**Describe the bug**
iwr : Richiesta annullata: Impossibile creare un canale sicuro SSL/TLS..
In riga:1 car:1
+ iwr -useb https://christitus.com/win | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], W
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![ice_screenshot_20220806-204625](https://user-images.githubusercontent.com/110740978/183262101-44fd23ea-1718-4d11-92b0-39ecdb97f423.png)

**Comment by Carterpersall** [comment] 2022-08-18 12:01
Duplicate of #88

**Comment by ChrisTitusTech** [comment] 2022-09-06 01:48
Fixed in PR #94

**Closed by ChrisTitusTech** 2022-09-06 01:48 UTC
