### ISSUE TITLE
Update (KB5046740) refuses to install

### ISSUE THREAD

**Issue by Mark112887** [ChrisTitusTech/winutil#3079] opened 2024-11-29 16:35 UTC
I can't actually find the direct reason as to why this update is failing to install. Admittedly, I don't know if it's because of the modifications that MicroWin has made to Windows 11. I'm hoping that someone could take a look and maybe try to find out what is causing this installation to fail.

**Comment by ethaantp** [comment] 2024-11-29 17:30
I've been having the same issue for a week or two on _stock_ ISOs after running the tweaks (and without using MicroWin on the ISO). I haven't had time run through and identify which settings are the cause, so here are the tweaks and customisations I've been using which should help reproduce the issue too.

![image](https://github.com/user-attachments/assets/ff78e3c9-3027-49bb-a31c-c6f3ec790ebd)

Apologies in advance if this is a red herring.

**Comment by CodingWonders** [comment] 2024-11-29 17:36
@Mark112887, I got the update to install:

![vmware_hDfZgGqria](https://github.com/user-attachments/assets/ac4dfc07-02d9-4d58-9f1b-b47ffe376851)

Have you applied any additional tweaks like @ethaantp said? Check and come back with the results.

Also, I recommend you look at the Windows Update logs, mainly `CBS.log` in `\Windows\Logs\CBS`. They can give us a clue

**Comment by Mark112887** [comment] 2024-11-29 17:40
> @Mark112887, I got the update to install:
> 
> ![vmware_hDfZgGqria](https://private-user-images.githubusercontent.com/101426328/391157966-ac4dfc07-02d9-4d58-9f1b-b47ffe376851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MDIyMDAsIm5iZiI6MTczMjkwMTkwMCwicGF0aCI6Ii8xMDE0MjYzMjgvMzkxMTU3OTY2LWFjNGRmYzA3LTAyZDktNGQ1OC05ZjFiLWI0N2ZmZTM3Njg1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxNzM4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzVkYmUwNDA2MTBhNzRkNTFiMTU1NGJhM2I3MjY3OWUxYjc3NjYzY2ZlZDNmMjAxZGI1NjMzZTgzYjE1MzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EXu3Yn1U3eb9SVpgGWrGe-vNStJfG5wq3n72N8wbc0s)
> 
> Have you applied any additional tweaks like @ethaantp said? Check and come back with the results.
> 
> Also, I recommend you look at the Windows Update logs, mainly `CBS.log` in `\Windows\Logs\CBS`. They can give us a clue. Please point the error code you're facing as well

no additional tweaks

**Comment by CodingWonders** [comment] 2024-11-29 17:41
@Mark112887, could you give me the additional information I asked?

**Comment by Mark112887** [comment] 2024-11-29 17:44
> @Mark112887, could you give me the additional information I asked?

the log?

**Comment by Mark112887** [comment] 2024-11-29 17:45
> @Mark112887, could you give me the additional information I asked?

ohhhh yes 0x800f081f

**Comment by CodingWonders** [comment] 2024-11-29 17:49
Could you give me the logs as well?

**Comment by Mark112887** [comment] 2024-11-29 18:01
[CBS.zip](https://github.com/user-attachments/files/17962134/CBS.zip)


> Could you give me the logs as well?

**Comment by Mark112887** [comment] 2024-11-29 22:16
> Could you give me the logs as well?

Want to report back. Decided to image my install and do an in place upgrade with the MicroWin USB. Since then, all updates have installed and my issue is resolved. So that was weird.

**Comment by CodingWonders** [comment] 2024-11-29 22:20
@Mark112887, it's also weird to me. I looked at the logs you provided and I could only spot errors about the legacy Media Player package. It's good to see that an in-place upgrade can help solve these issues.

Feel free to close this issue

**Closed** 2024-11-29 22:24 UTC
Labels: bug
