### ISSUE TITLE
Winget  Failing

### ISSUE THREAD

**Issue by ceramicv** [ChrisTitusTech/winutil#1881] opened 2024-04-25 18:18 UTC
**Describe the bug**
On older Windows 10 laptop trying to install software throws a winget error

**To Reproduce**
Check apps you want to install/upgrade, then click on that button. In the shell windows can see this output:

Program 'winget.exe' failed to run: The file cannot be accessed by the systemAt line:2640 char:35
+             $wingetVersionFull = (winget --version) # Full Version wi ...
+                                   ~~~~~~~~~~~~~~~~.
At line:2640 char:13
+             $wingetVersionFull = (winget --version) # Full Version wi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

You cannot call a method on a null-valued expression.
At line:2643 char:17
+             if ($wingetVersionFull.Contains("-preview")) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:2652 char:13
+             $wingetCurrentVersion = [System.Version]::Parse($wingetVe ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

===========================================
---        Winget is installed          ---
===========================================
Version:
    - Winget is a release version.
    - Winget is Out of Date
Getting Installed Programs...
Done...
===========================================
Error: Program 'winget.exe' failed to run: The file cannot be accessed by the systemAt line:28 char:35
+             $wingetVersionFull = (winget --version) # Full Version wi ...
+                                   ~~~~~~~~~~~~~~~~.
===========================================

**Expected behavior**
Applications to be installed/updated

**Screenshots**

**Additional context**

**Comment by blusewill** [comment] 2024-04-25 18:51
Sorry. Can you upload the text file to here?
Because of GitHub's Markdown Function, it's very hard to tell the issues

**Comment by Marterich** [comment] 2024-04-25 19:01
As far as i can Tell the Error seems to be `winget.exe' failed to run: The file cannot be accessed by the system` which occured the First time winutil tried to access winget to query the installed Version via `        $wingetVersionFull = (winget --version)`
I actually saw a similar behaviour willst experimenting for a previous PR,  but i have not managed to reproduce the Error Afterwards to find a true fix, so the best Option i can think of to handle this is to implement proper Error Handling in the function and throw an Error to manually upgrade winget. 

If anyone is able to prodive steps to reproduce the Error with the locked winget Ressource i would be Happy to try to implement a real fix

**Comment by ruxunderscore** [comment] 2024-05-03 19:10
> As far as i can Tell the Error seems to be `winget.exe' failed to run: The file cannot be accessed by the system` which occured the First time winutil tried to access winget to query the installed Version via ` $wingetVersionFull = (winget --version)` I actually saw a similar behaviour whiles experimenting for a previous PR, but i have not managed to reproduce the Error Afterwards to find a true fix, so the best option i can think of to handle this is to implement proper Error Handling in the function and throw an Error to manually upgrade winget.
> 
> If anyone is able to provide steps to reproduce the Error with the locked winget Ressource i would be happy to try to implement a real fix

Sounds like a simple fix. When I get home this evening, I can look at providing a solution for the error handling, if someone else doesn't get to it first. Otherwise, this does look like a $PATH issue, mentioned by @blusewill.

**Comment by Marterich** [comment] 2024-05-03 19:13
@ruxunderscore The simple Try Catch solution already got implemented (and merged) by @og-mrk 
Only the deepdive analysis into why winget is failing in the first place is still open, but i doubt that this will produce any meaningful output in the near future

**Comment by ruxunderscore** [comment] 2024-05-03 19:23
Got it, I noticed the age of the previous comments after I posted what I did. 😂 Works been busy.

**Closed** 2024-05-19 00:11 UTC
