### ISSUE TITLE
Alternative to winget if it fails

### ISSUE THREAD

**Issue by ghost** [ChrisTitusTech/winutil#384] opened 2022-11-16 18:58 UTC
**Is your feature request related to a problem? Please describe.**
Yes. Hi! so basically I cannot install winget due to some weird error on my custom windows iso. I think that the implementation of chocolatey as an alternative to winget (if winget fails) would be amazing!
**Describe the solution you'd like**
An alternative if winget fails to install.
**Describe alternatives you've considered**
Chocolatey
**Additional context**
No.

**Comment by lavavex** [comment] 2022-11-16 22:20
Winget is also currently failing on a clean windows 11 non custom install. tried updating the 'App Installer' package in windows store and error persists. 
`Failed in attempting to update the source: winget`
`Failed when searching source: winget`
`An unexpected error occurred while executing the command:`
`0x8a15000f: Data required by the source is missing`

**Comment by NerdHaxx** [comment] 2022-11-17 11:05
i meant that winget is not installed by default on my system and it is impossible for me to install it as my iso is heavily modified and gets process counts to ~50 soo system is also kinda broken (just the microsoft stuff is broken)

**Comment by ChrisTitusTech** [comment] 2023-07-12 19:09
Implementing fix... dupe of #347

**Closed by ChrisTitusTech** 2023-07-12 19:09 UTC
