### ISSUE TITLE
winutil(?) installs an unwanted app from ms store

### ISSUE THREAD

**Issue by asumika** [ChrisTitusTech/winutil#2385] opened 2024-07-17 00:45 UTC
Now I am not sure whether this is "expected" behavior from Microsoft's side or not, but I have tested winget on my own (manually via Terminal) and could only replicate this issue while using WinUtil. Upon installing basically any software through WinUtil, PowerShell immediately starts installing a program that is entirely unknown to me called "Advanced FlexiWingets (END USER TRIAL)" by a company named Aplicsoft. 
Aplicsoft themselves seem to be a Slovakian company specialising in UI/UX design and development in C#, but that isn't really the issue here. The Problem is that WinUtil takes this software from MS Store itself, in fact, the program itself can easily be found from MS Store: https://apps.microsoft.com/detail/9p5qj9mhb94t
but why is that? From what I see, the app is quite new (no reviews) and it is not mentioned on Aplicsoft's website so I can't see how it would be an important component to either WinUtil and/or Windows itself. I thought it would be important to report down here in case this is unwanted behavior. As web searching said program or even the company itself prompts me almost zero results.
![AsoI3oCrhv](https://github.com/user-attachments/assets/e70ea41e-b0d8-452a-8814-c980ac3faaf5)

**Comment by DcyMatrix** [comment] 2024-07-17 01:13
I can confirm this is happening. I tried twice selecting different programs, and it always install the app. FlexiWidgets (End User TRIAL) as the last thing it does.

**Comment by cakeDev45** [comment] 2024-07-17 02:14
I can also confirm this. When first setting up a new install of Windows 10 today, I used winutil and tried to install some programs from it and regardless of how many were selected, it would always install Advanced FlexiWidgets. This is a bit odd since this app was listed on the MS store just today.

**Comment by og-mrk** [comment] 2024-07-17 03:53
This looks like something odd indeed.. I noticed this behavior all the way back July the 6th (or so I believe, can't remember the exact day), where WinUtil tries to install `vSEC:CMS User` (MS Store app with ID `9NQZS0JTTWK7`).. at first I thought I was the only one getting this, but after looking around their website I noticed that it was saying something about AD (Active Directory, a feature mostly used by people using Office Products (which I do use Office for College)).. and I just brushed it off and didn't think about.

But after seeing this issue ticket, I went ahead and tried installing anything (even things that are already installed on my system, like PowerShell 7).. and indeed it was installing the exact software you've mentioned.

I'm still clueless on why it does this.. but I'll look into it and find the root cause of this Unwanted behavior. Thanks for reporting this @asumika 👍

**Comment by ChrisTitusTech** [comment] 2024-07-17 05:25
This was an unintended consequence from a bad for loop implementation. I reverted the changes in this commit:
https://github.com/ChrisTitusTech/winutil/commit/c90363181cf974c4342d5c3e01a58766d04cacf6

So this won't happen again. Thanks for letting me know!

**Comment by Marterich** [comment] 2024-07-19 19:52
Seeing that this should be fixed according to Chris and there was no protest, I'll close this issue.
If you still encounter problems, please let use know :) 
/close

**Closed** 2024-07-19 19:53 UTC
