### ISSUE TITLE
New Edge removal script doesn't work with Win10 32bit 

### ISSUE THREAD

**Issue by Freeman-ab** [ChrisTitusTech/winutil#2584] opened 2024-08-19 21:41 UTC
the new edge removal script doesn't work with win10 32bit. the message it gives is in the screenshot.

![message](https://github.com/user-attachments/assets/8c45eb3b-0609-404f-b101-f159853e2288)

**Comment by MyDrift-user** [comment] 2024-08-19 21:46
Does it only give the errors or does the removal itself not work?

bc while quickly looking at the image the only issues I found are registry keys that should be removed, but do not exist. So "technically" no "real" issues when thinking about the functionality of removing edge.

I did not code the removal itself, mentioning @psyirius to make him aware of the issue.

**Comment by Freeman-ab** [comment] 2024-08-19 21:48
edge is still there and working, nothing happened. it says "wow64" in the message. i think it's about 64bit version. so it cannot find  the 32bit edge, so doesn't do anything. not sure btw

**Comment by psyirius** [comment] 2024-08-19 21:49
Hmm... I think the reg keys used to lookup edge is focused on x64 alone.

I'll take a peek and update!

**Comment by alturic** [comment] 2024-08-23 02:00
I don't know if this is related, but removing Edge doesn't seem to work?

Under Tweaks I have Remove OneDrive and Remove Microsoft Edge checked, I click "Run Tweaks" and it says it ran both, but Edge is still installed? I reboot and go to Tweaks , click Get Installed and those two options are unchecked but everything else I've changed are checked... so I'm unsure where I'm going wrong? Granted if I check both, and click Run Tweaks it just seems like it runs the Edge tweak (no errors) but the OneDrive tweak says OneDrive wasn't found so I assume it's "working" per se but Edge is still installed.

**Comment by NotYourAverageGamer** [comment] 2024-08-23 03:22
Adding to this (i believe my issue is related)

I'm also unable to uninstall edge on Win11 Pro 23H2 64bit, i get the following:
![image](https://github.com/user-attachments/assets/f23f2d77-a544-425d-82a6-e1c4c42101be)
that is after trying to run `Uninstall Edge` from the `Install` Tab, then trying to run `Debloat Edge` and `Remove Microsoft Edge`

end result: edge is still installed on my system

**Comment by alturic** [comment] 2024-08-23 15:13
Interesting, unless all of that output is only shown/ran once I don’t believe I ever seen any of that.

I did read the “uninstall” has to be done via the Tweaks tab and not the uninstall tab like you would assume.

**Comment by WiLuX-Source** [comment] 2024-08-24 06:40
I tried out every script I can find on the internet but this software somehow manages to stick itself to the operating system again again...

**Comment by SoStressful** [comment] 2024-08-25 17:10
Can confirm I'm getting the same issue on Win11 Pro 23H2 64bit

![HI0M8Xl](https://github.com/user-attachments/assets/0436ac33-36ca-415c-9ab8-104338e09a24)
![QOTL9N6](https://github.com/user-attachments/assets/2f953bd7-5d27-4dba-bf54-77e0c39de679)

**Comment by psyirius** [comment] 2024-08-30 04:58
Looks like this won't be fixed!

Check: https://github.com/ChrisTitusTech/winutil/pull/2586

**Comment by alturic** [comment] 2024-08-30 12:13
I'm not exactly "good" with Github, but it looks like that is specific to x86, which I didn't even know there was working (joke but still) x86 hardware in the wild, especially Win10 installs.

Still looking for info on whether this can get fixed for Win11, and on x64.

**Comment by 4yman-0** [comment] 2024-09-18 18:47
This is a duplicate of (#2544 Removing Edge and Microsoft apps doesn't work).

**Comment by MyDrift-user** [comment] 2024-10-28 16:11
since the PR for the main request is closed and the rest of this discussion is about an issue that is already reported, I'm going to close this.

If you have a follow up question/request reopen this :)

/close

**Closed** 2024-10-28 16:11 UTC
