### ISSUE TITLE
WinUtil error

### ISSUE THREAD

**Issue by AndreyGasik** [ChrisTitusTech/winutil#2850] opened 2024-09-30 11:05 UTC
After use Microwin -Windows 26100.1742 became 26100.1 and outlook icon was in his place.

**Comment by CodingWonders** [comment] 2024-09-30 15:17
A fix is on its way

**Comment by AndreyGasik** [comment] 2024-09-30 15:18
Thanks bro!

**Comment by CodingWonders** [comment] 2024-09-30 15:34
@AndreyGasik, I thought the fix would be easy. Turns out it's harder than that. Because of that, you'll have to wait for the fix. For now, you can just re-apply the updates with Windows Update

**Comment by AndreyGasik** [comment] 2024-09-30 15:35
No problem. will be wait.

**Comment by CodingWonders** [comment] 2024-09-30 15:36
Please re-open the issue

**Comment by AndreyGasik** [comment] 2024-09-30 15:37
done

**Comment by CodingWonders** [comment] 2024-09-30 16:04
@AndreyGasik, doing the same stuff manually results in the same problem. The problem is that the base reset operation, which is required for cleaning the Windows image, causes DISM to get stuck at 71.6%.

Because of this, I can't think of a fix for this. You'll have to reapply the **cumulative update**

**Comment by AndreyGasik** [comment] 2024-09-30 16:06
This happens only in 24h2?

**Comment by CodingWonders** [comment] 2024-09-30 16:09
Yes. The thing is that the cumulative updates are not permanent, causing MicroWin to remove these.

In 23H2, however, these updates are permanent

**Comment by AndreyGasik** [comment] 2024-09-30 16:10
Ok, thanks for details.

**Comment by CodingWonders** [comment] 2024-12-24 07:05
Since we now have 24H2 ISOs from Microsoft and they share the same behavior with 23H2 (they've made those permanent updates permanent), this issue will be closed. /close

**Closed** 2024-12-24 07:05 UTC
