### ISSUE TITLE
[SOLVED] "Disable Telemetry" Tweak Causes Crashes with Full-screen Applications

### ISSUE THREAD

**Issue by JustTakingNotes** [ChrisTitusTech/winutil#122] opened 2022-09-12 02:39 UTC
RESOLUTION:
Use REGEDIT and navigate to: "HKCU:\Control Panel\Desktop" and delete the DWORD "HungAppTimeout"
Then Restart. This should fix flickers and fullscreen crashes.
If you continue to have issues you may consider also deleting these DWORDs within the same path: WaitToKillAppTimeout, AutoEndTasks, LowLevelHooksTimeout, and WaitToKillServiceTimeout as they are not native to the registry but are added by the Debloat Utility.
Restart after Registry changes to apply. Then reopen affected program.
Refer to attached picture below.

INITIAL PROBLEM:
After rebooting to apply "Disable Telemetry" tweak, full screen applications (games) will misbehave. The FS app will repeatedly "flicker" causing the desktop to momentarily become visible. In a multi-monitor setup you can see the app's taskbar icon shift to the end as if it were the last app started, even if it wasn't (the icon shifts as if the app were momentarily closed then rapidly restarted. It will continue doing this sliding motion concurrent with the "flickers"). ALT-TAB'ing out of the app will cause it to freeze and crash. 

I have experienced the issue with:
Steam Big-Picture
Sekiro (No flicker, ALT-TAB crash only)
Honkai 3rd Impact
Genshin Impact

Disabling Telemetry successfully reduces process count significantly and can be reversed by system restore. Bloated processes and FS app functionality restored upon system restore.

Only Telemetry Tweak caused instability from "Desktop" selection in Tweaks section.

Video of the Flickering:
https://www.youtube.com/watch?v=coqkDNgc0NM

![Delete This](https://user-images.githubusercontent.com/113319773/189720549-05c0e273-db8a-4e5c-847f-90787fed9379.png)

**Comment by ionascugabriel** [comment] 2022-09-12 12:13
I wanted to investigate more because i have the same issue and wanted to see if the cause were other options as well. It happened after i`ve applyed "Disable Telemetry".
For me it happens in desktop as you can see: random flickers, refresh, lost mouse contact of windows, unable to open random apps/games who are in taskbar or with alt+tab and generally some weird behavior.
It also happens in safemode.
For me using the "Undo al Tweaks" didn`t fix the isue.
![2022-09-12_15h01_11](https://user-images.githubusercontent.com/47446053/189650255-9ce511db-5663-4459-a68b-ee43f1b5b72c.gif)

**Comment by BauFender** [comment] 2022-09-12 12:47
It happens the same to me, I run desktop predefined tweaks and now I can not alt tab in full screen games like valorant or trackmania. Restore windows to an older point not fix the problem. Help :(

**Comment by ionascugabriel** [comment] 2022-09-12 12:51
Btw, can we have some temporary or hot fixes for this like some registry keys, services we can edit/enable?

**Comment by JustTakingNotes** [comment] 2022-09-12 13:56
I had to manually create a system restore point prior to performing the tweak to undo it. Using the undo tweaks option didn't fix the problem. You'll likely have to do a fresh install of windows if you didn't create your own restore point.

**Comment by BauFender** [comment] 2022-09-12 15:54
> You'll likely have to do a fresh install of windows if you didn't create your own restore point.

Not for me. Restore to a very old point not fix me the problem.

**Comment by JustTakingNotes** [comment] 2022-09-12 17:49
Fixed the issue on my computer. Edited top post. Please try and post results.

**Comment by ionascugabriel** [comment] 2022-09-12 18:02
@JustTakingNotes Thank you very much! for me worked with just "Use REGEDIT and navigate to: "HKCU:\Control Panel\Desktop" and delete the DWORD "HungAppTimeout"
Then Restart. This should fix flickers and fullscreen crashes."
All seems to work well so far. Well see how it goes. Again TY! (didn't really wanted to reainstall windows)

**Comment by JustTakingNotes** [comment] 2022-09-12 18:12
> ionascugabriel 
> lost mouse contact of windows

Another command in the telemetry tweaks was:
Set-ItemProperty -Path "HKCU:\Control Panel\Mouse" -Name "MouseHoverTime" -Type DWord -Value 10

If my solution above doesn't fix your mouse issue try restoring it to the default value of 400.

**Comment by ionascugabriel** [comment] 2022-09-12 18:18
> 

For now is working fine event with DWord -Value 10 but well remember this. TY.

**Comment by BauFender** [comment] 2022-09-12 20:19
@JustTakingNotes Thank youuuuuuu

**Comment by ChrisTitusTech** [comment] 2022-09-13 00:57
Thanks for posting this all. Posting a fix in the official script right now.

**Comment by ChrisTitusTech** [comment] 2022-09-13 01:03
Merged the following powershell command to fix this. Just rerunning the tweaks OR undo all will fix the issue. Commit: b3daa2f32ca4da7f2c46691970ccc3ce328c1455

Or just type this in powershell `Remove-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name "HungAppTimeout" -ErrorAction SilentlyContinue`

**Closed by ChrisTitusTech** 2022-09-13 01:03 UTC
