### ISSUE TITLE
Quiet Mode

### ISSUE THREAD

**Issue by AlessandroFasse** [ChrisTitusTech/winutil#352] opened 2022-11-04 09:12 UTC
Would it be possible to implement a `quiet mode` for the tool? 

So that for example you could define a list of components you want to have/apply using a `.yaml` file or similar and then call the tool with the corresponding arguments like `--quiet --config config.yaml` ? That would be very nice because I would like to use the tool on a couple of servers I don't want to click trough the tool 30 times by hand :)

**Comment by 0nelight** [comment] 2022-11-19 16:41
This is a duplicate of #130.

**Closed** 2022-11-30 21:22 UTC
