### ISSUE TITLE
can't install windows terminal in windows 10 pro N version 21H2 (OS Build 19044.1889)

### ISSUE THREAD

**Issue by Erlan-w** [ChrisTitusTech/winutil#363] opened 2022-11-06 12:20 UTC
**Describe the bug:**
When I put command to install **windows terminal** on windows 10 pro N version 21H2 (OS Build 19044.1889), Windows PS gives me error

I'm using **Windows PowerShell 5.1 and I'm trying on ps 7.2.6** too, running as administrator
and run the command **irm christitus.com/win | iex**

but still error

Please help me

Screenshot

![image](https://user-images.githubusercontent.com/80790147/200168860-9afa45cc-9ae1-4ecb-8235-d21499f92d11.png)

**Comment by ChrisTitusTech** [comment] 2023-07-12 17:17
Dupe of #347 Will fix in next update

**Closed by ChrisTitusTech** 2023-07-12 17:17 UTC
