### ISSUE TITLE
winscp and rust remote desktop install problem

### ISSUE THREAD

**Issue by conkerts** [ChrisTitusTech/winutil#323] opened 2022-10-23 20:00 UTC
**Describe the bug**
I selected winscp and rust remote desktop but the script doesn't install them.

**To Reproduce**
select winscp and rust remote desktop 
click start install
*crickets*  (aka asks me to select programs despite them being selected)

**Expected behavior**
installation

**Screenshots**
...

**Additional context**
I'm using the latest version ofc via git checkout

**Comment by DeveloperDurp** [comment] 2022-10-24 11:53
What happens when you run the script directly from the repository? 

`iwr -useb https://christitus.com/win | iex`

**Comment by conkerts** [comment] 2022-10-24 17:38
well, pretty much the same
![image](https://user-images.githubusercontent.com/35889937/197590326-0e6c3ed1-13d5-43a9-b1fb-059c529a6802.png)

Also, idk if it is of any use, but the terminal output is
```
====Chris Titus Tech=====
=====Windows Toolbox=====
Checking if Winget is Installed...
Winget Already Installed
```

**Comment by DeveloperDurp** [comment] 2022-10-24 17:55
Will be resolved as soon as the hotfix gets merged

**Comment by Carterpersall** [comment] 2022-11-04 17:18
@conkerts as the issue is resolved, please close the issue

**Closed** 2022-11-04 17:22 UTC
