### ISSUE TITLE
WINGET 

### ISSUE THREAD

**Issue by KALIXHOSTING** [ChrisTitusTech/winutil#947] opened 2023-08-08 13:02 UTC
![Screenshot 2023-08-08 at 7 56 26 AM](https://github.com/ChrisTitusTech/winutil/assets/93708739/6aac9407-b921-468b-8930-b2ec591a75d3)

WINGET INSTALL Is still not working keep on getting winget install failed when you try to install a package

**Comment by ChrisTitusTech** [comment] 2023-08-08 21:36
Dupe of #943

**Closed by ChrisTitusTech** 2023-08-08 21:36 UTC

**Comment by KALIXHOSTING** [comment] 2023-08-20 13:14
The Issue is occurring on windows server 2022 It was working before when you did your youtube video  https://www.youtube.com/watch?v=anibuEt1pzg  But now it's Not Working I did install winget but for some reason the script its still not detecting install 

![winutil](https://github.com/ChrisTitusTech/winutil/assets/93708739/756d55f7-c76b-46ad-949b-bc4782c08a88)
