### ISSUE TITLE
Error after today's update.

### ISSUE THREAD

**Issue by Hellements** [ChrisTitusTech/winutil#155] opened 2022-09-15 20:50 UTC
**Describe the bug**
After today's update, when I go to Tweaks section and click on Desktop, Laptop or Minimal I get a red text error on the PowerShell window as you can see on the screenshot.

**To Reproduce**
1. Go to Tweaks
2. Click on Desktop, Laptop or Minimal
3. See error on PowerShell

**Expected behavior**
Tool woks with no errors.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/88634350/190506140-9acd74a1-28e8-48b8-a96e-6b7bd481275e.jpg)

**Additional context**
I'm on win10pro 21h2 build 190441889

**Comment by PrincessAkira** [comment] 2022-09-18 22:55
aye.
thats my thing.
i think i missed smth somewhere.
il look into it 👍

**Comment by PrincessAkira** [comment] 2022-09-18 23:25
Ah forgot to add it in the XML on my commit that was in the PR.
![image](https://user-images.githubusercontent.com/45071533/190932634-bf8999c2-b1ac-443c-b476-ec364198da0c.png)

**Comment by PrincessAkira** [comment] 2022-09-18 23:29
So i commited #165 now.
hopefully its right this time.
testing it via local xml gives me a bunch of errors so i cant really do it atm

**Comment by kAMENkitA** [comment] 2022-09-19 10:28
![powershell_ym37L4JnXe](https://user-images.githubusercontent.com/87366745/190998043-7bf0e420-5adb-486f-a621-058d7f3392be.png)

Happening similar to me after applying desktop Tweaks...

![image](https://user-images.githubusercontent.com/87366745/190998305-ce5a1141-f03c-494e-b401-d85030a36df8.png)
![image](https://user-images.githubusercontent.com/87366745/190998594-ddf98f1a-c702-41fd-97de-48a8c1fd18ed.png)

**Comment by PrincessAkira** [comment] 2022-09-19 16:44
> **Describe the bug** After today's update, when I go to Tweaks section and click on Desktop, Laptop or Minimal I get a red text error on the PowerShell window as you can see on the screenshot.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Tweaks
> 2. Click on Desktop, Laptop or Minimal
> 3. See error on PowerShell
> 
> **Expected behavior** Tool woks with no errors.
> 
> **Screenshots** ![Untitled](https://user-images.githubusercontent.com/88634350/190506140-9acd74a1-28e8-48b8-a96e-6b7bd481275e.jpg)
> 
> **Additional context** I'm on win10pro 21h2 build 190441889

can you try again?

**Comment by kAMENkitA** [comment] 2022-09-20 07:31
Now is much better... :)
![image](https://user-images.githubusercontent.com/87366745/191194757-3c9abfc7-c10b-45d6-84f2-353c66c47075.png)

I managed by hitting Powershell with "Run As Admin" !! 
That's the catch.

**Comment by Hellements** [comment] 2022-09-20 15:44
Hello,
Unfortunately, the problem persists for me.
I'm running the tool on PowerShell as admin with the command "iwr -useb https://christitus.com/win | iex"
![Untitled](https://user-images.githubusercontent.com/88634350/191303060-4de9c551-a470-4746-a9dd-0a2c8e617201.jpg)
Thanks.

**Comment by SkyFoxCoder** [comment] 2022-09-20 18:51
@PrincessAkira Hey, the (likely) problem is that you are adding "WPF" before "Misc" in the XML file, by following the convention that other objects are using, the "XML" text is added automatically in front of the name when made available in Powershell's code.

So, "WPFMiscTweakDisableUAC" becomes "WPFWPFMiscTweakDisableUAC" when accessed from powershell.

Try to following the code conventions! :D It's both a much better practice, and in that case, prevents errors/problems. 👍

**Comment by SkyFoxCoder** [comment] 2022-09-20 18:58
@ChrisTitusTech
The original problem should be fixed by @PrincessAkira changes (I tested myself), this issue should be closed and other problems should have their own issues 👍

**Comment by SkyFoxCoder** [comment] 2022-09-21 02:03
> Hello, Unfortunately, the problem persists for me. I'm running the tool on PowerShell as admin with the command "iwr -useb https://christitus.com/win | iex" ![Untitled](https://user-images.githubusercontent.com/88634350/191303060-4de9c551-a470-4746-a9dd-0a2c8e617201.jpg) Thanks.

The fix isn't pushed to the released version, it's not possible to use it yet.

@ChrisTitusTech I've confirmed that the changes are fixing the original issue on the test branch, since the PR has been merged, this can be closed.

**Comment by kAMENkitA** [comment] 2022-09-21 07:52
Thank You all again for your hard-work on this great Utility !!

**Closed** 2022-09-21 13:56 UTC
