### ISSUE TITLE
Winutil shortcut broke

### ISSUE THREAD

**Issue by michaeldun123** [ChrisTitusTech/winutil#2510] opened 2024-08-03 14:36 UTC
## Describe the bug
Myself and my father use WinUtil on a regular basis, and we have found that WinUtil shortcut doesn't re-open the winutil prompt

## To Reproduce
1. Open up WinUtil
2. Click on Tweaks
3. Click on Create winutil shortcut
4. Make the Shortcut
5. Close out of WinUtil
6. Click on the shortcut

## Expected behavior
Should re-open winutil using PWSH or Powershell

## Screenshots

![ezgif-1-886e637a20](https://github.com/user-attachments/assets/e82b6810-306e-4037-8766-b9c2c6ed93a5)

**Comment by NotYourAverageGamer** [comment] 2024-08-04 07:38
duplicate of #2487
would be fixed by #2488

**Comment by michaeldun123** [comment] 2024-08-04 08:46
> duplicate of #2487
> 
> would be fixed by #2488 
> 
> 
> 
> Manual fix: https://github.com/ChrisTitusTech/winutil/issues/2487#issuecomment-2265224487

Yeah, realised that afterwards

**Closed** 2024-08-06 17:53 UTC
