### ISSUE TITLE
MicroWin - Explorer.exe freezes when double clicking any drive.

### ISSUE THREAD

**Issue by Beaverhoosen** [ChrisTitusTech/winutil#1316] opened 2023-12-26 22:24 UTC
I was playing with the MicroWin ISO modifier (no drivers added during the creation of the image ) to install Windows 11 Pro. The system is an AMD Ryzen 3600 CPU system with an Asus Strix B550 Gaming Wifi, Explorer.exe freezes when trying to access ANY drive listed. 

Image Version: Win11_23H2_EnglishInternational_x64v2

Reinstalled twice from new images and installed the latest AMD chipset drivers, also used the Wintool System Corruption Scan and it did not fix the issue.

Everything else loaded and appeared to work as expected. Had to revert back to installing the unadulterated version Win11_23H2_EnglishInternational_x64v2.

**Comment by MichTheOcelot** [comment] 2023-12-27 02:27
someone provided a version of a fork with a supposed fix for this but it has since been removed, this is still a reocurring issue

**Comment by sigma2017** [comment] 2023-12-27 09:21
I have experienced exactly the same behavior on my AMD Ryzen 5900x CPU on MSI B450 Tomahawk Max using the microwin.iso I created starting from latest 23h2. Had to reinstall one more time from scratch using the official image from Microsoft.
As I already explained into Discussion section, this microwin.iso file is kinda fine into virtual environment where I created a virtual machine from this iso. I am using Vmware workstation PRO v17. I haven't included any drivers when I created the microwin.iso either....
Any chances to repair this blocking issue? 
Thanks.

**Comment by fruselight** [comment] 2023-12-29 06:27
I've found a temporary fix from #1276
Basically you need to start EventLog service and set it to Automatic.

**Comment by sigma2017** [comment] 2023-12-30 09:10
Actually the issue is happening into my VM as well.
The temporary fix is working, just set Windows Event Log to Automatic and reboot, manually start doesn't help.
Thanks!

**Comment by CodingWonders** [comment] 2024-01-03 17:01
I've made a temporary workaround in `MicroWin-Helper.ps1` that detects if the service is "EventLog" and skips it.

It's in PR #1346

**Comment by KonTy** [comment] 2024-01-04 01:20
> Actually the issue is happening into my VM as well. The temporary fix is working, just set Windows Event Log to Automatic and reboot, manually start doesn't help. We need to wait some time until everything will be merged into the main branch. Thanks!

When you set it to automatic does explorer start working or it is still having issues? I'mm wondering if you are still seeing issues is it soemthing else and not the EventLog issue.

**Closed** 2024-02-20 03:46 UTC
