### ISSUE TITLE
Very high CPU usage with GUI

### ISSUE THREAD

**Issue by mistamal** [ChrisTitusTech/winutil#2208] opened 2024-06-28 18:07 UTC
**Describe the bug**
Very high GPU usage when using the GUI utility launched from powershell

**To Reproduce**
run iwr -useb https://christitus.com/win | iex on powershell as admin

**Expected behavior**
low GPU usage.

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/30079306/e215964f-1958-4030-8aaa-6aaacd778ed0)
![image](https://github.com/ChrisTitusTech/winutil/assets/30079306/639c2014-2fef-412e-9933-de916ff57e63)

**Additional context**
note that the GPU is the intel UHD iGPU, not the Nvidia eGPU.

**Comment by Marterich** [comment] 2024-06-28 19:37
Please run
 `Get-CimInstance Win32_VideoController | fl Name`
In an administrative Powershell and post the results here so we can check if your GPU needs to be added to the blacklist for gpus that struggle with the matrix theme.

Fyi: the GPU blacklisting system got optimized a few days ago and will become available in the next release.

**Comment by MyDrift-user** [comment] 2024-06-28 20:13
What I think happened is WinUtil detected the NGIDIA GPU and therefore used a ressource demanding UI, but that GPU is not the one used, so the integraded Graphics are way overloaded.

If you are using a PC, you should plug in your Monitor to the GPU, that are usually the horizontal video ports. If you plug it in to the Mainboard (vertical ones) it always uses the Intel UHD Graphics.

A way to fix that issue in general is to change the way WinUtil detects the GPU, I will look into it that weekend if noone already did.

**Comment by mistamal** [comment] 2024-06-28 20:23
> Please run `Get-CimInstance Win32_VideoController | fl Name` In an administrative Powershell and post the results here so we can check if your GPU needs to be added to the blacklist for gpus that struggle with the matrix theme.
> 
> Fyi: the GPU blacklisting system got optimized a few days ago and will become available in the next release.

Thanks for looking into this! Here is the output of the above command.

Name : Intel(R) UHD Graphics 630

Name : NVIDIA GeForce GTX 1650

**Comment by mistamal** [comment] 2024-06-28 20:25
> What I think happened is WinUtil detected the NGIDIA GPU and therefore used a ressource demanding UI, but that GPU is not the one used, so the integraded Graphics are way overloaded.
> 
> If you are using a PC, you should plug in your Monitor to the GPU, that are usually the horizontal video ports. If you plug it in to the Mainboard (vertical ones) it always uses the Intel UHD Graphics.
> 
> A way to fix that issue in general is to change the way WinUtil detects the GPU, I will look into it that weekend if noone already did.

Actually I am on a Dell XPS 7590 laptop which has a single HDMI output, so I assume the system determines automatically which GPU to use based on the application.

**Comment by Marterich** [comment] 2024-06-28 20:28
> > Please run `Get-CimInstance Win32_VideoController | fl Name` In an administrative Powershell and post the results here so we can check if your GPU needs to be added to the blacklist for gpus that struggle with the matrix theme.
> > 
> > Fyi: the GPU blacklisting system got optimized a few days ago and will become available in the next release.
> 
> Thanks for looking into this! Here is the output of the above command.
> 
> Name : Intel(R) UHD Graphics 630
> 
> Name : NVIDIA GeForce GTX 1650

All Right, this problem was already fixed in #2178 and will be resolved for you once the new winutil release is published :) so there's nothing more to do

**Comment by og-mrk** [comment] 2024-07-07 11:49
Hello @mistamal 
Just checking if the problem is fixed in the latest WinUtil release?
If it's fixed, then please consider closing this issue as complete, and if not (the issue still present) then I recommend keeping this issue open & If possible, provide any additional info which might help in further debugging of issue. Thanks in advance 😄

**Comment by mistamal** [comment] 2024-07-15 00:15
Hello! sorry for the delayed response...

I can confirm that the iGPU is not being taxed abnormally. Thank you for resolving this issue and maintaining this project!

**Comment by Marterich** [comment] 2024-07-15 06:39
@mistamal great to hear your issue is resolved. Could you mark the issue as resolved/closed please :)

**Comment by og-mrk** [comment] 2024-07-17 10:06
> Hello! sorry for the delayed response...
> 
> I can confirm that the iGPU is not being taxed abnormally. Thank you for resolving this issue and maintaining this project!

Happy to hear that, and no problem on the late reply.
Considering that the issue you're facing is resolved, I'll be closing this Issue Ticket, Thanks for reporting this problem @mistamal 😄

/close

**Closed** 2024-07-17 10:06 UTC
