### ISSUE TITLE
MicroWin wrongly removed Windows Defender

### ISSUE THREAD

**Issue by andreinoue** [ChrisTitusTech/winutil#1339] opened 2024-01-03 02:03 UTC
**Describe the bug**
The Windows 11 version I created using MicroWin apparently hasn't got Windows Defender, even though I ticked the "Keep Windows Defender" box in the process of creating the ISO.

**To Reproduce**
1. Download Win11_23H2_EnglishInternational_x64v2.iso from https://www.microsoft.com/en-us/software-download/windows11/.
2. Tick boxes "Keep Windows Defender" and "Keep Microsoft Edge".
3. Follow Microwin instructions, selecting Windows 11 Pro as the SKU.
4. Use the microwin.iso to fresh install Windows 11
5. Go to Settings > Privacy & security > Windows security
6. Click on "Open Windows Security"
7. See error

**Expected behavior**
Expected Windows Defender to be present in microwin.iso

**Screenshots**
![image](https://github.com/ChrisTitusTech/winutil/assets/85354782/0fb5465e-7101-477c-a96f-2e9cd3137219)
![image](https://github.com/ChrisTitusTech/winutil/assets/85354782/c7435866-4afd-4807-9e94-0ece50858447)

**Additional context**
Just noticed there is a "Windows Defender" and a "Windows Defender Advanced Threat Protection" folder in the Program Files, though.

**Comment by MichTheOcelot** [comment] 2024-01-03 07:08
same issue here.

**Comment by CodingWonders** [comment] 2024-01-03 10:01
This could be because of the Windows Security AppX package being removed, but I'm not sure. I'll investigate this issue.

**Comment by CodingWonders** [comment] 2024-01-03 11:00
Confirmed: it is that.

An AppX package in the listing is `Microsoft.SecHealthUI_1000.22621.1.0_x64__8wekyb3d8bbwe`, which is Windows Security:

```powershell
[DBG]: PS C:\dev>> $appxProvisionedPackages | Select-Object -ExpandProperty PackageName
Clipchamp.Clipchamp_2.2.8.0_neutral_~_yxz26nhyzhsrt
Microsoft.549981C3F5F10_3.2204.14815.0_neutral_~_8wekyb3d8bbwe
Microsoft.BingNews_4.2.27001.0_neutral_~_8wekyb3d8bbwe
Microsoft.BingWeather_4.53.33420.0_neutral_~_8wekyb3d8bbwe
Microsoft.GamingApp_2021.427.138.0_neutral_~_8wekyb3d8bbwe
Microsoft.GetHelp_10.2201.421.0_neutral_~_8wekyb3d8bbwe
Microsoft.Getstarted_2021.2204.1.0_neutral_~_8wekyb3d8bbwe
Microsoft.HEIFImageExtension_1.0.43012.0_x64__8wekyb3d8bbwe
Microsoft.HEVCVideoExtension_1.0.50361.0_x64__8wekyb3d8bbwe
Microsoft.MicrosoftOfficeHub_18.2204.1141.0_neutral_~_8wekyb3d8bbwe
Microsoft.MicrosoftSolitaireCollection_4.12.3171.0_neutral_~_8wekyb3d8bbwe
Microsoft.MicrosoftStickyNotes_4.2.2.0_neutral_~_8wekyb3d8bbwe
Microsoft.Paint_11.2201.22.0_neutral_~_8wekyb3d8bbwe
Microsoft.People_2020.901.1724.0_neutral_~_8wekyb3d8bbwe
Microsoft.PowerAutomateDesktop_10.0.3735.0_neutral_~_8wekyb3d8bbwe
Microsoft.RawImageExtension_2.1.30391.0_neutral_~_8wekyb3d8bbwe
Microsoft.ScreenSketch_2022.2201.12.0_neutral_~_8wekyb3d8bbwe
Microsoft.SecHealthUI_1000.22621.1.0_x64__8wekyb3d8bbwe
```

I'll add detections for that option and exclude it from the listing

**Comment by CodingWonders** [comment] 2024-01-03 12:02
This issue is fixed in my fork. You will need to perform MicroWin processing once again.

```powershell
irm https://raw.githubusercontent.com/CodingWonders/winutil/CW-MicroWin-AppxFix/winutil.ps1 | iex
```

**Comment by CodingWonders** [comment] 2024-01-03 12:55
> @CodingWonders would you recommend running the entire MicroWin process once again or would just downloading the Windows Defender app from Microsoft Store suffice?

I don't know if you can just download Windows Security from the Store (it's a system component after all), so I recommend redoing MicroWin

**Comment by andreinoue** [comment] 2024-01-03 12:59
Interestingly enough, it is on the Microsoft Store:
![image](https://github.com/ChrisTitusTech/winutil/assets/85354782/0d035963-5359-475e-a801-2bc65170491c)
It seems you need a Microsoft subscription, though, so I think I'll just run MicroWin again.

**Comment by CodingWonders** [comment] 2024-01-03 13:00
> Interestingly enough, it is on the Microsoft Store: ![image](https://private-user-images.githubusercontent.com/85354782/293918700-0d035963-5359-475e-a801-2bc65170491c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODcwNzEsIm5iZiI6MTcwNDI4Njc3MSwicGF0aCI6Ii84NTM1NDc4Mi8yOTM5MTg3MDAtMGQwMzU5NjMtNTM1OS00NzVlLWE4MDEtMmJjNjUxNzA0OTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEyNTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZjJiMDFhYmM2MzkxNGU2YTkyNjJhMzNlODUyMmM3ZGU4ZDMxMDZiYTZlYjg2YmEyNDA1NWU1YjFiZWMwZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.71-MlO9bkrshsVaYkWzjnqu2TFyuRIQNnWn2p4a08zA) It seems you need a Microsoft subscription, though, so I think I'll just run MicroWin again.

That's a different app.

**Comment by andreinoue** [comment] 2024-01-03 13:04
Ah, lol. No option, then. Thanks!

**Closed** 2024-01-03 15:52 UTC
